"{\"success\":false,\"header\":null,\"data\":null,\"messageKey\":\"error.404\",\"message\":\"error.404\",\"errors\":[],\"exceptions\":[{\"messageData\":{},\"resource\":\"Throwable\",\"messageKey\":\"Throwable\",\"message\":\"Throwable with cause of type 'com.manh.cp.fw.core.exception.ManhRuntimeException' was caught and handled by CustomErrorController (see logs for the trace)\",\"stackTrace\":\"java.lang.Throwable: Throwable with cause of type 'com.manh.cp.fw.core.exception.ManhRuntimeException' was caught and handled by CustomErrorController (see logs for the trace)\\n\"}],\"messages\":{\"Message\":[{\"Type\":\"ERROR\",\"Code\":\"Location\",\"Description\":\"Location not found for business keys: locationId: Outlet.\",\"ShortDescription\":null,\"ErrorCode\":\"fwe::10064\",\"ErrorField\":null,\"ResourceId\":null,\"QuickInfo\":false,\"BusinessKeys\":null}],\"Size\":1},\"rootCause\":\"java.lang.Throwable: Throwable with cause of type 'com.manh.cp.fw.core.exception.ManhRuntimeException' was caught and handled by CustomErrorController (see logs for the trace)\",\"cloudComponent\":\"com-manh-cp-fulfillment:docker,cloud,kubernetes:8080\",\"cloudComponentHostName\":\"738782b5781f\",\"requestUri\":\"/error\",\"statusCode\":\"BAD_REQUEST\"}"