"{\"success\":false,\"header\":null,\"data\":null,\"messageKey\":\"org::10036\",\"message\":\"org::10036\",\"errors\":[],\"exceptions\":[{\"messageData\":{},\"resource\":\"Throwable\",\"messageKey\":\"Throwable\",\"message\":\"Throwable with cause of type 'com.manh.cp.fw.entity.exception.ManhValidationException' was caught and handled by CustomErrorController (see logs for the trace)\",\"stackTrace\":\"java.lang.Throwable: Throwable with cause of type 'com.manh.cp.fw.entity.exception.ManhValidationException' was caught and handled by CustomErrorController (see logs for the trace)\\n\"}],\"messages\":{\"Message\":[{\"Type\":\"ERROR\",\"Code\":\"org::10036\",\"Description\":\"Provisioning profile FB-BRAND1-CANADA-S and Organization FB-BRAND1-CANADA-S cannot have details with invalid profile IDs: [Profile-FB-CANADA-S]\",\"ShortDescription\":null,\"ErrorCode\":null,\"ErrorField\":null,\"ResourceId\":null,\"QuickInfo\":false,\"BusinessKeys\":null}],\"Size\":1},\"rootCause\":\"java.lang.Throwable: Throwable with cause of type 'com.manh.cp.fw.entity.exception.ManhValidationException' was caught and handled by CustomErrorController (see logs for the trace)\",\"cloudComponent\":\"com-manh-cp-organization:docker,cloud,kubernetes:8080\",\"cloudComponentHostName\":\"cab3009d57db\",\"requestUri\":\"/error\",\"statusCode\":\"BAD_REQUEST\"}"